#pragma once

// Custom shadow node for RichChatInputView that enables native Yoga measurement.
// This file is NOT generated by codegen, so it survives codegen reruns.
// We define a NEW class name (RichChatInputMeasuringShadowNode) to avoid any
// conflict with the codegen typedef in ShadowNodes.h.

#include <react/renderer/components/RichChatInputViewSpec/EventEmitters.h>
#include <react/renderer/components/RichChatInputViewSpec/Props.h>
#include <react/renderer/components/view/ConcreteViewShadowNode.h>
#include <react/renderer/core/ConcreteComponentDescriptor.h>
#include <react/renderer/core/LayoutConstraints.h>
#include <react/renderer/core/LayoutContext.h>
#include <react/renderer/componentregistry/ComponentDescriptorProviderRegistry.h>
#include <jsi/jsi.h>
#include <algorithm>

namespace facebook::react {

// RichChatInputViewComponentName is defined in the codegen-generated ShadowNodes.cpp.
// We declare it here so we can use it as a template parameter.
JSI_EXPORT extern const char RichChatInputViewComponentName[];

// State data for native height measurement.
// contentHeight is set from the UITextView's sizeThatFits result (main thread)
// via state->updateState(), which triggers a Yoga re-layout without JS.
struct RichChatInputMeasuringStateData {
    float contentHeight{0.0f};
    bool operator==(const RichChatInputMeasuringStateData &rhs) const {
        return contentHeight == rhs.contentHeight;
    }
    bool operator!=(const RichChatInputMeasuringStateData &rhs) const {
        return !(*this == rhs);
    }
};

class RichChatInputMeasuringShadowNode final
    : public ConcreteViewShadowNode<
          RichChatInputViewComponentName,
          RichChatInputViewProps,
          RichChatInputViewEventEmitter,
          RichChatInputMeasuringStateData> {
public:
    // Inherit all base constructors (including the clone constructor).
    // Traits are copied during cloning so the MeasureLayout trait propagates
    // to clones without needing to re-call enableMeasurement().
    using ConcreteViewShadowNode::ConcreteViewShadowNode;

    // Initial-construction constructor: enable native Yoga measurement.
    RichChatInputMeasuringShadowNode(
        const ShadowNodeFragment &fragment,
        const ShadowNodeFamily::Shared &family,
        ShadowNodeTraits traits)
        : ConcreteViewShadowNode(fragment, family, traits) {
        enableMeasurement();
    }

    // Called by Yoga to determine the component's size during layout.
    // Returns the height stored in Fabric state (set from the UITextView's
    // sizeThatFits on the main thread), clamped to Yoga's layout constraints.
    Size measureContent(
        const LayoutContext & /*layoutContext*/,
        const LayoutConstraints &layoutConstraints) const override {
        Float height = (Float)getStateData().contentHeight;
        if (height < 1.0f) {
            // No height measured yet; use minimum (initial single-line height).
            return {layoutConstraints.maximumSize.width,
                    layoutConstraints.minimumSize.height};
        }
        height = std::max(height, layoutConstraints.minimumSize.height);
        height = std::min(height, layoutConstraints.maximumSize.height);
        return {layoutConstraints.maximumSize.width, height};
    }
};

using RichChatInputMeasuringComponentDescriptor =
    ConcreteComponentDescriptor<RichChatInputMeasuringShadowNode>;

} // namespace facebook::react
